import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Softles - Web Design & Development Agency London - SoftLes",
  description: "Generated by create next app",
};

import AnimatedCursor from "./components/_components/AnimatedCursor"; // Import AnimatedCursor

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased cursor-default-hidden`} // Added custom class for cursor hiding
      >
        <AnimatedCursor /> {/* Add the animated cursor component */}
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
